### ISSUE TITLE
Usage for library?

### ISSUE THREAD

**Issue by SeedyROM** [janestreet/cohttp_async_websocket#5]
I'm attempting to use this library to create a simple Websocket server that will send a message and then shutdown. I took some code from the tests to try and see if I can use it at all.

When I attempt to connect from a websocket connection I get the following error:

```
2023-08-02 03:45:29.564313-04:00 Error ("Failed to validate apparent websocket request"("Missing one of origin or host header"(origin())(host(127.0.0.1:8080)))((headers((Host 127.0.0.1:8080)(Connection Upgrade)(Upgrade websocket)(Sec-WebSocket-Version 13)(Sec-WebSocket-Key 3VdMuORPq43kxERdMwjKvQ==)))(meth GET)(scheme())(resource /)(version HTTP_1_1)(encoding Unknown)))
```

Here is the example code:

```ocaml
open Async

let websocket_server =
  let open Cohttp_async_websocket in
  let handle_request ~inet:_ ~subprotocol:_ _request =
    Server.On_connection.create (fun websocket ->
        let _, writer = Websocket.pipes websocket in
        Pipe.write writer "hello world")
    |> return
  in
  Server.create
    ~non_ws_request:(fun ~body:_ ->
      failwith "got a request that wasn't websocket!")
    handle_request

let start ~port =
  let open Cohttp_async in
  let%bind server =
    Server.create_expert
      (Tcp.Where_to_listen.of_port port)
      ~on_handler_error:`Raise websocket_server
  in
  Server.close_finished server

```

**Comment by SeedyROM** [comment]
Wait, can I not connect to this library without the port being 80 or 443?

https://github.com/janestreet/cohttp_async_websocket/blob/583d3cb43f490d8b8f81fcf89841226e6adeaccd/src/header.ml#L178

That seems a bit weird...

**Comment by SeedyROM** [comment]
So I sat around looking at the source code for this library and realized I can just handle any incoming ws:// request as a websocket connection with the following code:

Code that changed was the `Cohttp_async_websocket.Server.create` argument `~should_process_request:
      (fun (_ : Socket.Address.Inet.t) _header ~is_websocket_request:_ -> Ok ())`.

```ocaml
open Async
open Core

let websocket_server =
  let open Cohttp_async_websocket in
  let handle_request ~inet:_ ~subprotocol:_ _request =
    Server.On_connection.create (fun websocket ->
        let _, writer = Websocket.pipes websocket in
        Pipe.write writer "hello world")
    |> return
  in
  Server.create
    ~should_process_request:
      (fun (_ : Socket.Address.Inet.t) _header ~is_websocket_request:_ -> Ok ())
    ~non_ws_request:(fun ~body:_ ->
      failwith "got a request that wasn't websocket!")
    handle_request

let start ~port =
  let open Cohttp_async in
  let%bind server =
    Server.create_expert
      (Tcp.Where_to_listen.of_port port)
      ~on_handler_error:`Raise websocket_server
  in
  Server.close_finished server
```

I'm sure I can check the url of the request to match a path like `/ws` but this works for me for now.

**Comment by TyOverby** [comment]
Yeah, the default implementation of `should_process_request` verifies that the websocket connection is being established from the same domain that the websocket server is being hosted on.

**Comment by SeedyROM** [comment]
Would you accept a PR with a basic usage for servers in `/examples`? I could make that clearly documented and I'd love for other people trying to use this library not to have to dig immediately into the source!

**Comment by TyOverby** [comment]
That'd be lovely, thank you!
